name: Flutter Firebase Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter doctor
        run: flutter doctor -v

      # APK for testing
      - name: Build APK
        run: flutter build apk --debug

      # AAB for Play Store
      - name: Build AAB
        run: flutter build appbundle --debug

      # Web build (optional)
      - name: Build Web
        run: flutter build web

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # Upload AAB
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: build/app/outputs/bundle/debug/app-debug.aab

      # Upload Web
      - name: Upload Web
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
